name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libnoise-dev

    - name: Build on GCC
      if: matrix.compiler == 'gcc'
      run: |
        sudo apt-get install -y g++
        run ./build.sh -c gcc

    - name: Build on Clang
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get install -y clang
        run ./build.sh -c clang

